site_name: PHALCON
docs_dir: docs
nav:

  - Home: index.md
  - Tutorial 1- Running PHALCON on simulated datasets: simulation.md
  - Tutorial 2- AML-67-001 (AML Targeted Sequencing Panel): aml_67_001.md
  - Tutorial 3- TN4 (TNBC Targeted Sequencing Panel): tnbc.md

theme:
  name: readthedocs
  logo: images/PHALCON_logo.png
